### ISSUE TITLE
Can´t install/execute because of numpy error

### ISSUE THREAD

**Issue by diovon** [varungupta31/dashcam_anonymizer#10]
Hi,
first of all, I find dashcam_anonymizer fantastic and really like to use it.
I plan to publish some videos from my daily bike trips and that would be very helpful.

I sadly fail at the installation, because I get an error at the installation of numpy.

Sorry I'm not so familiar with coding and searching on the net didn't get me a solution.
```
Collecting numpy==1.25.1
  Using cached numpy-1.25.1.tar.gz (10.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "/home/andreas/git/dashcam_anonymizer/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/andreas/git/dashcam_anonymizer/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/andreas/git/dashcam_anonymizer/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "/home/andreas/git/dashcam_anonymizer/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/andreas/anaconda3/lib/python3.12/importlib/__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 995, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "/tmp/pip-build-env-cqeaaq_r/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "/tmp/pip-build-env-cqeaaq_r/overlay/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/tmp/pip-build-env-cqeaaq_r/overlay/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Have you a hint or solution for me?

**Comment by diovon** [comment]
I searched more and found out that numpy is not compatible to my python version 3.12

I have downgraded to python 3.11 and than the installation works for numpy, but not it fails for opencv-4.6.0. This error says it needs python 3.12, I'm now confused.

```
Using cached PyYAML-6.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (757 kB)
Building wheels for collected packages: pycocotools
  Building wheel for pycocotools (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pycocotools (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [60 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build/lib.linux-x86_64-cpython-311/pycocotools
      copying pycocotools/__init__.py -> build/lib.linux-x86_64-cpython-311/pycocotools
      copying pycocotools/coco.py -> build/lib.linux-x86_64-cpython-311/pycocotools
      copying pycocotools/mask.py -> build/lib.linux-x86_64-cpython-311/pycocotools
      copying pycocotools/cocoeval.py -> build/lib.linux-x86_64-cpython-311/pycocotools
      running build_ext
      /tmp/pip-build-env-pl613_cw/overlay/lib/python3.11/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pip-install-fl2jenpb/pycocotools_1fcdf78c7a6b42299b3b83342250dc84/pycocotools/_mask.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      Compiling pycocotools/_mask.pyx because it changed.
      [1/1] Cythonizing pycocotools/_mask.pyx
      building 'pycocotools._mask' extension
      creating build/temp.linux-x86_64-cpython-311/common
      creating build/temp.linux-x86_64-cpython-311/pycocotools
      x86_64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -g -fwrapv -O2 -fPIC -I/tmp/pip-build-env-pl613_cw/overlay/lib/python3.11/site-packages/numpy/core/include -I./common -I/home/andreas/git/dashcam_anonymizer/venv/include -I/usr/include/python3.11 -c ./common/maskApi.c -o build/temp.linux-x86_64-cpython-311/./common/maskApi.o -Wno-cpp -Wno-unused-function -std=c99
      ./common/maskApi.c: In function ‘rleToBbox’:
      ./common/maskApi.c:151:32: warning: unused variable ‘xp’ [-Wunused-variable]
        151 |     uint h, w, xs, ys, xe, ye, xp, cc; siz j, m;
            |                                ^~
      ./common/maskApi.c: In function ‘rleFrPoly’:
      ./common/maskApi.c:197:3: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
        197 |   for(j=0; j<k; j++) x[j]=(int)(scale*xy[j*2+0]+.5); x[k]=x[0];
            |   ^~~
      ./common/maskApi.c:197:54: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘for’
        197 |   for(j=0; j<k; j++) x[j]=(int)(scale*xy[j*2+0]+.5); x[k]=x[0];
            |                                                      ^
      ./common/maskApi.c:198:3: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
        198 |   for(j=0; j<k; j++) y[j]=(int)(scale*xy[j*2+1]+.5); y[k]=y[0];
            |   ^~~
      ./common/maskApi.c:198:54: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘for’
        198 |   for(j=0; j<k; j++) y[j]=(int)(scale*xy[j*2+1]+.5); y[k]=y[0];
            |                                                      ^
      ./common/maskApi.c: In function ‘rleToString’:
      ./common/maskApi.c:243:7: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
        243 |       if(more) c |= 0x20; c+=48; s[p++]=c;
            |       ^~
      ./common/maskApi.c:243:27: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
        243 |       if(more) c |= 0x20; c+=48; s[p++]=c;
            |                           ^
      ./common/maskApi.c: In function ‘rleFrString’:
      ./common/maskApi.c:251:3: warning: this ‘while’ clause does not guard... [-Wmisleading-indentation]
        251 |   while( s[m] ) m++; cnts=malloc(sizeof(uint)*m); m=0;
            |   ^~~~~
      ./common/maskApi.c:251:22: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘while’
        251 |   while( s[m] ) m++; cnts=malloc(sizeof(uint)*m); m=0;
            |                      ^~~~
      ./common/maskApi.c:259:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
        259 |     if(m>2) x+=(long) cnts[m-2]; cnts[m++]=(uint) x;
            |     ^~
      ./common/maskApi.c:259:34: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
        259 |     if(m>2) x+=(long) cnts[m-2]; cnts[m++]=(uint) x;
            |                                  ^~~~
      x86_64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -g -fwrapv -O2 -fPIC -I/tmp/pip-build-env-pl613_cw/overlay/lib/python3.11/site-packages/numpy/core/include -I./common -I/home/andreas/git/dashcam_anonymizer/venv/include -I/usr/include/python3.11 -c pycocotools/_mask.c -o build/temp.linux-x86_64-cpython-311/pycocotools/_mask.o -Wno-cpp -Wno-unused-function -std=c99
      pycocotools/_mask.c:47:10: fatal error: Python.h: Datei oder Verzeichnis nicht gefunden
         47 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycocotools
Failed to build pycocotools
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pycocotools)
Requirement already satisfied: opencv-python in ./venv/lib/python3.11/site-packages (4.10.0.84)
Requirement already satisfied: numpy>=1.21.2 in ./venv/lib/python3.11/site-packages (from opencv-python) (2.1.2)
Channels:
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: - warning  libmamba Added empty dependency for problem type SOLVER_RULE_UPDATE
failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package opencv-4.6.0-py310h1128e8f_3 requires python >=3.10,<3.11.0a0, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ opencv 4.6.0**  is installable with the potential options
│  ├─ opencv 4.6.0 would require
│  │  └─ python >=3.10,<3.11.0a0 , which can be installed;
│  ├─ opencv 4.6.0 would require
│  │  └─ python >=3.11,<3.12.0a0 , which can be installed;
│  ├─ opencv 4.6.0 would require
│  │  └─ python >=3.7,<3.8.0a0 , which can be installed;
│  ├─ opencv 4.6.0 would require
│  │  └─ python >=3.8,<3.9.0a0 , which can be installed;
│  └─ opencv 4.6.0 would require
│     └─ python >=3.9,<3.10.0a0 , which can be installed;
└─ pin-1 is not installable because it requires
   └─ python 3.12.* , which conflicts with any installable versions previously reported.
```

**Comment by varungupta31** [comment]
Hey @diovon,
sure, let's try to get those biking videos uploaded!

It seems you are using `conda` to manage your environments.
If so, you're most likely doing this, I guess:

```bash
$ conda create --name dash python==3.10 -y
$ conda activate dash
```
then from within the repo folder,

```bash
$ chmod +x setup.sh
$ ./setup.sh
```

If not, can you try doing exactly this - and lmk if it works?

**Comment by diovon** [comment]
Seems I still get an error.

fyi, my system is xubuntu 24.04

-so I run your calls
```
conda create --name dash python==3.10 -y
conda activate dash
./setup.sh
```

But sadly it still has some dependency issues. I tried to test with the test videos you share in your repo.

see file: [terminal_log.txt](https://github.com/user-attachments/files/17356931/terminal_log.txt)

**Comment by varungupta31** [comment]
I think you're almost there, the numpy dependency seems to have been taker care of, you might just need to do

`pip install rich`

and the environment setup should be done, try running the python script.

If not,

I replicated the `setup.sh` on my Ubuntu just now, it works - I wonder what breaks in yours OS.

Then I'd start over  --> in the `setup.sh` I'll remove the `numpy` things and let the packages manage which numpy they want.

updated `setup.sh`

```bash
pip install ultralytics==8.0.144
pip install pybboxes
pip install opencv-python
conda install opencv=4.6.0
pip install gdown
mkdir model
echo "Downloading the YOLO model..."
gdown 1uV8IMuGDbmDabdjyeSy4SUKV9OS-ULbe
mv best.pt model/
echo "Setup complete!"
```

This should not give any numpy conflicts, i think.

In my environment,
ultimately these packages were installed

```
gdown                     5.2.0                    pypi_0    pypi
numpy                     1.24.2                   pypi_0    pypi
ultralytics               8.0.144                  pypi_0    pypi
```

if this also doesnt work, try specifying the `gdown` version in your case to this as well.

**Comment by diovon** [comment]
I'm also confused about my environment. It is a new installation of xubuntu 24.04, because the update process didn't worked for me.

First of all I want to thank you for your time to help me with my system settings 

Hm, yes I had to install 2 additional packages:

```
pip install rich
pip install natsort
```

with this packages I'm now able to blur the sample photos. Great.

BUT, sadly blurring the sample video I still get an error.

log_file: 
[blur_video_log.txt](https://github.com/user-attachments/files/17368523/blur_video_log.txt)

I started again new.

Removed conda packages

```
conda clean -a 
```

and followed your instructions with the edited setup-file.

```
pip install ultralytics==8.0.144
pip install pybboxes
pip install opencv-python
conda install opencv=4.6.0
pip install gdown
mkdir model
echo "Downloading the YOLO model..."
gdown 1uV8IMuGDbmDabdjyeSy4SUKV9OS-ULbe
mv best.pt model/
echo "Setup complete!"
```

And this time it also worked for photos, but not for videos.

I modified the vid_blur.yaml and set the parameter `gpu_avail: False` because I just have an old thinkpad (x250).

Then the log looks a little bit better. Now it seems to have an issue with the color definition `orange`.

```
python blur_videos.py --config configs/vid_blur.yaml
Reading the Configuration file from configs/vid_blur.yaml
Loading YOLO Model...
/home/andreas/anaconda3/envs/dash/lib/python3.10/site-packages/ultralytics/nn/tasks.py:561: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  return torch.load(file, map_location='cpu'), file  # load
Generating YOLO Detections for the Videos
Traceback (most recent call last):
  File "/home/andreas/git/dashcam_anonymizer/blur_videos.py", line 44, in <module>
    console.print("GPU Not Available, Running on CPU", style="bold orange")
  File "/home/andreas/anaconda3/envs/dash/lib/python3.10/site-packages/rich/console.py", line 1710, in print
    render(renderable, render_options), self.get_style(style)
  File "/home/andreas/anaconda3/envs/dash/lib/python3.10/site-packages/rich/console.py", line 1483, in get_style
    raise errors.MissingStyle(
rich.errors.MissingStyle: Failed to get style 'bold orange'; unable to parse 'orange' as color; 'orange' is not a valid color
```

Have you another hint for me?

**Comment by diovon** [comment]
Update: also video blurring is working.

I just changed the styling parameter from orange to green and the script started running.

Maybe it is an issue with my zsh-environment, so the color can't be used.

Thank you again for your patient and your help.

**Comment by varungupta31** [comment]
> Maybe it is an issue with my zsh-environment, so the color can't be used.


Yeah, not with `zsh` but terminal itself. Not all terminals support all format and styles.

Without a GPU, running this on a video would be a pain (too slow).
Could try google colab, upload your videos to google drive, and search how to 'mount' google drive to colab.

Good luck!
